baseURL = '/'
languageCode = 'en-us'
title = "mads' hack"
theme = 'hugo-book'
paginate = 20
enableGitInfo = true
type = 'docs'
disableKinds = ['taxonomy']

[params]

  BookTheme = 'light'

  BookToC = true

  #BookLogo = 'logo.png'

  BookMenuBundle = '/menu'

  BookSection = 'docs'

  BookDateFormat = 'Jan 2, 2006'

  BookSearch = true

  BookComments = true

  BookPortableLinks = true

  BookServiceWorker = true
