baseURL = '/'
languageCode = 'en-us'
title = "mads' corner of internet"
theme = 'bare'
paginate = 20
enableGitInfo = true

[taxonomies]
  category = "categories"

[params]
mainSections = ["posts"]
author = "madshckd"
email = "madshckd@gmail.com"
description = 'gopher and more..'
postcss = false
includeAuthorInTitle = true
hero_colour = "info"
disableAttribution = true

[markup.highlight]
noClasses = false
theme = "monokai"

[[params.social]]
icon = "github"
url = "https://github.com/madshckd/"
